user susshi;
worker_processes  1;

error_log  /opt/wasabi/susshi-chef/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    map $ssl_client_s_dn $ssl_client_s_dn_cn {
        default "";
        ~CN=(?<CN>[^/,\"]+) $CN;
    }

    map $time_iso8601 $year {
        default 'date';
        '~^(?<yyyy>\d{4})-' $yyyy;
    }

    map $time_iso8601 $month {
        default 'not';
        '~^\d{4}-(?<mm>\d{2})-' $mm;
    }

    map $time_iso8601 $day {
        default 'found';
        '~^\d{4}-\d{2}-(?<dd>\d{2})' $dd;
    }

    map $time_iso8601 $logfile_date {
        default 'date-not-found';
        '~^(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})' $year-$month-$day;
    }

    log_format  api   '$remote_addr - $ssl_client_s_dn_cn [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" $upstream_response_time';

    log_format  main  '$remote_addr - $ssl_client_s_dn_cn [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /opt/wasabi/susshi-chef/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server_tokens off;

    include /opt/wasabi/susshi-chef/config/nginx/conf.d/sic-ssl.conf;
    include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-http.conf;
    include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl.conf;
}
