# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

assets:
  secret_key_base: 9e8011f5f471ebe5c6e228232109887c3ce67cff3085cae91c4b116a2571ca8b0b972b0d81e1994bcd40b2d3b7ac6b707271242be9d3fe5eefc1246e24a158be

development:
  secret_key_base: 381b4d18b8a60d8ce16adc19155d702171f571ed285127d57649b0da07cf74694744d18e3af26915936f003f40c6ec500020f8dc4a05c77224339a3f574339cb

test:
  secret_key_base: c3f0b582f92e167ae5a5fd3931c44da1a8ece3f91078a1efccda2971f358adb75377cc09a7d27ee91dc511d691a9a3e933746eea6d693eab616aaee1b55b78e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# The secret here is overridden at least by bin/susshi-chef on startup or ENV-variable
# It's only purpose is calling rake tasks from cronjobs like chef:purge_logs_and_reports and chef:garbage_ip_caching

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
