server {
    listen              443 ssl;
    listen              [::]:443 ssl;

    http2               on;

    server_name         _;

    root                /opt/wasabi/susshi-chef/public;

    ssl_certificate     ssl/server.crt;
    ssl_certificate_key ssl/server.key;

    include             /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-proto.conf;
    ssl_prefer_server_ciphers off;

    add_header          Strict-Transport-Security "max-age=31536000; includeSubDomains;";

    error_log           /opt/wasabi/susshi-chef/log/nginx/ui/error.log  error;
    access_log          /opt/wasabi/susshi-chef/log/nginx/ui/$logfile_date-access.log  main;

    include             /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-cc-1.conf;

    location ~ "^/api/v[0-9]+/(config|config/|operations/)" {
        include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-cc-2.conf;

        error_log   /opt/wasabi/susshi-chef/log/nginx/api/error.log  error;
        access_log  /opt/wasabi/susshi-chef/log/nginx/api/$logfile_date-access.log  api;

        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_read_timeout 600s;
        proxy_redirect off;

        proxy_pass http://127.0.0.1:3000;
    }

    location /api/ {
        rewrite ^/api/.*$ /403 last;
    }

    location ~ "^/assets/.+-[0-9a-f]{32}.*" {
        include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-cc-2.conf;

        gzip_static on;
        expires max;
        add_header Cache-Control public;
    }

    location /favicon.ico {
        include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-cc-2.conf;

        gzip_static on;
        expires max;
        add_header Cache-Control public;
    }

    location /target_hosts/scan/execute {
        include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-cc-2.conf;

        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_read_timeout 900s;
        proxy_redirect off;

        proxy_pass http://127.0.0.1:3000;
    }

    location / {
        include /opt/wasabi/susshi-chef/config/nginx/conf.d/ui-ssl-cc-2.conf;

        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_read_timeout 600s;
        proxy_redirect off;

        proxy_pass http://127.0.0.1:3000;
    }
}
